palette = 'catppuccin'

format = """
$directory\
$git_branch\
$git_status\
$git_state\
$nodejs\
$rust\
$docker_context\
$fill\
$jobs\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline = true
scan_timeout = 15
command_timeout = 1000

[palettes.catppuccin]
overlay = '#313244'
muted   = '#6c7086'
subtle  = '#a6adc8'
text    = '#cdd6f4'
love    = '#f38ba8'
gold    = '#f9e2af'
rose    = '#fab387'
pine    = '#89b4fa'
foam    = '#89dceb'
iris    = '#89dceb'

[directory]
truncation_length = 3
truncation_symbol = '../'
style = 'bold foam'
read_only = ' 󰌾'
read_only_style = 'love'
format = '[$path]($style)[$read_only]($read_only_style) '

[fill]
symbol = '─'
style = 'overlay'

[git_branch]
format = '[$symbol$branch]($style) '
style = 'iris'
symbol = ' '

[git_status]
format = '([$all_status]($style) )'
style = 'love'
conflicted = '✚'
untracked  = '✚'
stashed    = '✚'
modified   = '✚'
staged     = '✚'
renamed    = '✚'
deleted    = '✚'
ignore_submodules = true

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = 'bold gold'

[nodejs]
format = '[$symbol$version]($style) '
style = 'gold'
symbol = ' '
detect_extensions = ['js', 'mjs', 'cjs', 'ts']
detect_files = ['package.json']
detect_folders = ['node_modules']

[rust]
format = '[$symbol$version]($style) '
style = 'gold'
symbol = ' '

[docker_context]
format = '[$symbol$context]($style) '
style = 'foam'
symbol = ' '
only_with_files = true

[jobs]
symbol = '●'
style = 'love'
format = '[$number $symbol]($style) '
threshold = 1
number_threshold = 1

[cmd_duration]
format = '[$duration]($style) '
style = 'rose'
min_time = 2_000
show_milliseconds = false

[time]
disabled = false
format = '[$time]($style)'
style = 'subtle'
time_format = '%H:%M'

[character]
success_symbol = '[❯](pine)'
error_symbol = '[❯](love)'
vimcmd_symbol = '[❮](foam)'
