#!/usr/bin/env bash
# Pulls secrets from Bitwarden and writes config.js.
# Run once on new machine setup or after rotating Strava tokens.
#
# Bitwarden item name: firefox-feed
# Required custom fields: strava_client_id, strava_client_secret,
#                         strava_refresh_token, av_key
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${DIR}/config.js"
ITEM_NAME="firefox-feed"

_field() { printf '%s' "${1}" | jq -r --arg n "${2}" '.fields[] | select(.name==$n) | .value'; }

for cmd in bw jq; do
  command -v "${cmd}" &>/dev/null || {
    echo "error: ${cmd} not found — install: sudo pacman -S ${cmd/bw/bitwarden-cli}" >&2
    exit 1
  }
done

status=$(bw status 2>/dev/null | jq -r '.status // "unauthenticated"')

[[ "${status}" == "unauthenticated" ]] && { bw login; status=$(bw status | jq -r '.status'); }
[[ "${status}" == "locked"          ]] && { export BW_SESSION; BW_SESSION=$(bw unlock --raw); }

bw sync --quiet

item=$(bw get item "${ITEM_NAME}" 2>/dev/null) || {
  echo "error: item '${ITEM_NAME}' not found in Bitwarden" >&2
  echo "  Create a Login or Secure Note item named '${ITEM_NAME}' with custom fields:" >&2
  echo "  strava_client_id, strava_client_secret, strava_refresh_token, av_key" >&2
  exit 1
}

strava_id=$(_field "${item}"     "strava_client_id")
strava_secret=$(_field "${item}" "strava_client_secret")
strava_refresh=$(_field "${item}" "strava_refresh_token")
av_key=$(_field "${item}"        "av_key")

[[ -z "${strava_id}" || -z "${strava_secret}" || -z "${strava_refresh}" || -z "${av_key}" ]] && {
  echo "error: one or more fields empty in Bitwarden item '${ITEM_NAME}'" >&2
  echo "  Required: strava_client_id, strava_client_secret, strava_refresh_token, av_key" >&2
  exit 1
}

cat > "${OUT}" <<EOF
// Auto-generated by gen-config.sh — do not edit manually.
// Regenerate: bash firefox-feed/gen-config.sh
window.STRAVA_CREDS = {
  clientId:     '${strava_id}',
  clientSecret: '${strava_secret}',
  refreshToken: '${strava_refresh}',
};
window.GH_CREDS = { token: '' };
window.AV_KEY = '${av_key}';
EOF

echo "→ ${OUT} written"
