#!/usr/bin/env bash
# Regenerates gh-data.js using the gh CLI (gh auth login handles auth + SSO).
# Fetches: contribution counts, user profile, repo list.
# Run manually or via hypr-firefox-watch.py (triggered on Firefox open).
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
WEEK_AGO="$(date -u -d '7 days ago' +"%Y-%m-%dT%H:%M:%SZ")"
CUR_YEAR="$(date +%Y)"
USERNAME="$(gh api user --jq '.login')"

CONTRIBS="totalCommitContributions totalIssueContributions totalPullRequestContributions totalPullRequestReviewContributions restrictedContributionsCount"
CALENDAR="contributionCalendar { weeks { contributionDays { date contributionCount } } }"

# Build year aliases — each includes totals + full calendar for historic monthly chart
yr_blocks=""
for i in 0 1 2 3 4; do
  yr=$(( CUR_YEAR - i ))
  from="${yr}-01-01T00:00:00Z"
  to="$( [[ $i -eq 0 ]] && echo "$NOW" || echo "$((yr+1))-01-01T00:00:00Z" )"
  yr_blocks+="    yr${yr}: contributionsCollection(from: \"${from}\", to: \"${to}\") { ${CONTRIBS} ${CALENDAR} }"$'\n'
done

# Write GraphQL query to temp file
QUERY_FILE="$(mktemp)"
cat > "$QUERY_FILE" <<GRAPHQL
{
  user(login: "${USERNAME}") {
    w: contributionsCollection(from: "${WEEK_AGO}", to: "${NOW}") {
      ${CONTRIBS}
    }
${yr_blocks}  }
}
GRAPHQL

# Fetch all data via Python (handles pagination and JSON assembly cleanly)
python3 - "$QUERY_FILE" "$DIR/gh-data.js" <<'PYEOF'
import subprocess, json, sys, os
from datetime import datetime

query_file, out_file = sys.argv[1], sys.argv[2]

# Load existing data — used to preserve entries from other machines
existing = {}
if os.path.exists(out_file):
    try:
        raw = open(out_file).read()
        existing = json.loads(raw.split('window.GH_DATA = ')[1].rstrip(';\n'))
    except Exception:
        pass

# Contributions (GraphQL)
r = subprocess.run(['gh', 'api', 'graphql', '-F', f'query=@{query_file}'], capture_output=True, text=True, check=True)
contributions = json.loads(r.stdout)

# User profile (slim)
r = subprocess.run([
    'gh', 'api', 'user',
    '--jq', '{login:.login,public_repos:.public_repos,followers:.followers,following:.following,html_url:.html_url}',
], capture_output=True, text=True, check=True)
profile = json.loads(r.stdout)

# Repos (paginated, up to 500) — this machine's visible scope
current_repos = []
for page in range(1, 6):
    r = subprocess.run([
        'gh', 'api',
        f'/user/repos?visibility=all&affiliation=owner,collaborator,organization_member&sort=pushed&direction=desc&per_page=100&page={page}',
    ], capture_output=True, text=True, check=True)
    batch = json.loads(r.stdout or '[]')
    current_repos.extend({
        'name':             x['name'],
        'html_url':         x['html_url'],
        'private':          x['private'],
        'language':         x['language'],
        'stargazers_count': x['stargazers_count'],
        'description':      x['description'],
    } for x in batch)
    if len(batch) < 100:
        break

# Merge repos: carry forward repos from other machines, let current data override
merged = {r['html_url']: r for r in existing.get('repos', [])}
for r in current_repos:
    merged[r['html_url']] = r
repos = list(merged.values())

# Commit counts per language — per-repo so each machine only updates its scope.
# Structure: { html_url: { lang, count } }
repo_commits = dict(existing.get('repo_commits', {}))
owned = [x for x in current_repos if x['html_url'].split('/')[-2] == profile['login']]
for repo in owned:
    lang = repo.get('language')
    if not lang:
        continue
    try:
        r = subprocess.run(
            ['gh', 'api',
             f'/repos/{profile["login"]}/{repo["name"]}/commits?author={profile["login"]}&per_page=100'],
            capture_output=True, text=True, check=True,
        )
        repo_commits[repo['html_url']] = {'lang': lang, 'count': len(json.loads(r.stdout or '[]'))}
    except Exception:
        pass

# Aggregate for display
lang_commits = {}
for entry in repo_commits.values():
    lang_commits[entry['lang']] = lang_commits.get(entry['lang'], 0) + entry['count']

# Aggregate monthly contribution counts across all year blocks
calendar_months = {}
for key, val in (contributions.get('data', {}).get('user', {}) or {}).items():
    if not key.startswith('yr') or not val:
        continue
    for week in val.get('contributionCalendar', {}).get('weeks', []):
        for day in week.get('contributionDays', []):
            mo = day['date'][:7]
            calendar_months[mo] = calendar_months.get(mo, 0) + day['contributionCount']

payload = json.dumps({
    'data':             contributions.get('data'),
    'profile':          profile,
    'repos':            repos,
    'repo_commits':     repo_commits,
    'lang_commits':     lang_commits,
    'calendar_months':  calendar_months,
})

with open(out_file, 'w') as f:
    f.write(f'// Auto-generated by refresh-gh.sh — do not edit manually.\n')
    f.write(f'// Regenerate: bash firefox-feed/refresh-gh.sh\n')
    f.write(f'// Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
    f.write(f'window.GH_DATA = {payload};\n')

print(f'→ {out_file} updated ({len(repos)} repos total, {len(owned)} owned, {len(lang_commits)} langs, {datetime.now().strftime("%H:%M:%S")})')
PYEOF

rm -f "$QUERY_FILE"
